version: '3.8'
services:
  shareit-gateway:
    build: shareit-gateway
    image: shareit-gateway-image
    container_name: shareit-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHAREIT_SERVER_URL=http://shareit-server:9090

  shareit-server:
    build: shareit-server
    image: shareit-server-image
    container_name: shareit-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:14-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
